<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\Tags\HasTags;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Relations\MorphToMany;


class Post extends Model implements HasMedia
{
    use HasFactory;
    use HasTags;
    use InteractsWithMedia;


    public const TYPE_LINK = 'link';
    public const TYPE_ORIGINAL = 1;

    protected $fillable =[
        "title",
        "text",
        "slug",
        "user_id",
        "description",
        "category_id",
        "featured_image",
        "publish_date",
        "external_url",
        "published",
        'post_thumbnail',
        "original_content"
    ];



    public function tags(): MorphToMany
    {
        return $this
            ->morphToMany(self::getTagClassName(), 'taggable', 'taggables', null, 'tag_id')
            ->orderBy('order_column');
    }


    public function getKeyName()
    {
        return parent::getKeyName(); // TODO: Change the autogenerated stub
    }

    public function category(): BelongsTo
    {
        return $this->BelongsTo(Category::class);
    }





    public function user(): BelongsTo
    {
        return $this->BelongsTo(User::class);
    }


    protected function getThumbnailAttribute()
    {
        $mediaItems = $this->getMedia();
        if (!empty($mediaItems) && isset($mediaItems[0])) {
            return $mediaItems[0]->getFullUrl();
        }

        return  asset('images/default-thumbnail.jpg');

    }


    public function isOriginal(): Attribute
    {

        if($this->original_content) {
            return new Attribute(function () {
                return  static::TYPE_ORIGINAL;
            });
        }


        return new Attribute(function () {
            return $this->original_conten;
        });


    }



    public function url(): Attribute
    {
        if($this->original_content) {
            return new Attribute(function () {
                return route('blog.show', ['blog' => $this->slug]);
            });
        }

        return new Attribute(function () {
            return $this->external_url;
        });
    }



    public  function  readingTime(): Attribute
    {
        return  new Attribute(function (){
            return Str::readDuration($this->text). ' min read';
        });

    }


    public  function  publishedDate(): Attribute
    {
        return  new Attribute(function (){
            return date("F d, Y", strtotime($this->created_at));
        });

    }



    public function thumbnail()
    {
        return Storage::disk('admin-uploads')->url($this->post_thumbnail);
    }

}
